import { useEffect, useMemo, useState } from "react";
import { AnimatedContent, AnimatedMetric } from "./components/AnimatedContent.jsx";

const OPERATIONS = ["set", "get", "delete", "range"];

export default function App() {
  const [apiBase, setApiBase] = useState(process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8080");
  const [structures, setStructures] = useState([]); const [structure, setStructure] = useState(""); const [selectedStructures, setSelectedStructures] = useState([]);
  const [operation, setOperation] = useState("get"); const [datasetSize, setDatasetSize] = useState(100); const [seed, setSeed] = useState(42); const [captureTrace, setCaptureTrace] = useState(true);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null); const [traceIndex, setTraceIndex] = useState(-1); const [playing, setPlaying] = useState(false); const [dragged, setDragged] = useState(null);
  const trace = result?.trace || [];
  const metadata = useMemo(() => structures.find((item) => item.name === structure)?.complexity?.find((item) => item.operation === operation), [structures, structure, operation]);

  useEffect(() => { let cancelled = false; fetch(`${apiBase.replace(/\/$/, "")}/api/v1/structures`).then((response) => { if (!response.ok) throw Error(); return response.json(); }).then((items) => { if (!cancelled) { setStructures(items); setStructure(items[0]?.name || ""); setSelectedStructures(items.slice(0, 2).map((item) => item.name)); } }).catch(() => { if (!cancelled) setError("The experiment service is not reachable. Start the API or check the deployment configuration."); }); return () => { cancelled = true; }; }, [apiBase]);
  useEffect(() => { if (!playing || !trace.length) return undefined; const timer = setInterval(() => setTraceIndex((current) => { if (current >= trace.length - 1) { setPlaying(false); return current; } return current + 1; }), 700); return () => clearInterval(timer); }, [playing, trace.length]);

  async function runExperiment(event) { event.preventDefault(); if (datasetSize < 0 || datasetSize > 100000 || seed < 0 || !structure) { setError("Use a supported structure and non-negative values within the dataset limit."); return; } setLoading(true); setError(""); setPlaying(false); setTraceIndex(-1); const input = operation === "range" ? { name: operation, start: "a", end: "z" } : { name: operation, key: "demo-key", value: "demo-value" }; try { const response = await fetch(`${apiBase.replace(/\/$/, "")}/api/v1/experiments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ structure, dataset_size: Number(datasetSize), seed: Number(seed), trace: captureTrace, operations: [input] }) }); const body = await response.json(); if (!response.ok) throw Error(body.code || "experiment_failed"); setResult(body); setTraceIndex(body.trace?.length ? 0 : -1); } catch (runError) { setError(`Could not run experiment (${runError.message}).`); } finally { setLoading(false); } }
  function toggleStructure(name) { setStructure(name); setSelectedStructures((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]); }
  function moveStructure(target) { if (!dragged || dragged === target) return; setSelectedStructures((current) => { const next = [...current]; const from = next.indexOf(dragged), to = next.indexOf(target); if (from < 0 || to < 0) return current; next.splice(from, 1); next.splice(to, 0, dragged); return next; }); setDragged(null); }

  return <main className="shell"><header className="topbar"><div><p className="eyebrow">AlgoDB Lab / experiment lab</p><h1>Data structure laboratory</h1><p className="lede">Choose an implementation for the database, run a workload, and follow its execution path.</p></div></header>
    <section className="workspace"><form className="controls" onSubmit={runExperiment}><Heading number="01" title="Configure run"/><div className="structure-picker"><div className="picker-label">Data structures <small>Click to activate. Select multiple to compare.</small></div>{structures.map((item) => <label className={`structure-option ${selectedStructures.includes(item.name) ? "selected" : ""} ${structure === item.name ? "active" : ""}`} key={item.name} draggable={selectedStructures.includes(item.name)} onClick={() => setStructure(item.name)} onDragStart={() => setDragged(item.name)} onDragOver={(event) => event.preventDefault()} onDrop={() => moveStructure(item.name)}><input type="checkbox" checked={selectedStructures.includes(item.name)} onChange={() => toggleStructure(item.name)} /><span className="structure-swatch" />{item.name}<small>{structure === item.name ? "active" : "compare"}</small></label>)}</div><Field label="Operation"><select value={operation} onChange={(event) => setOperation(event.target.value)}>{OPERATIONS.map((item) => <option key={item} value={item}>{item}</option>)}</select></Field><div className="two-up"><Field label="Dataset size"><input type="number" min="0" max="100000" value={datasetSize} onChange={(event) => setDatasetSize(event.target.value)} /></Field><Field label="Seed"><input type="number" min="0" value={seed} onChange={(event) => setSeed(event.target.value)} /></Field></div><label className="check"><input type="checkbox" checked={captureTrace} onChange={(event) => setCaptureTrace(event.target.checked)} /> Capture execution trace</label><button className="run" disabled={loading}><span>{loading ? "Running…" : "Run experiment"}</span><span aria-hidden="true">→</span></button><p className="form-error" role="alert">{error}</p></form>
      <section className="results"><Heading number="02" title="Database view" extra={result ? `${result.structure} / ${operation}` : "Waiting for a run"}/><DatabaseView structures={selectedStructures} active={structure} trace={trace}/><div className="metric-grid"><AnimatedMetric active={Boolean(result)} label="Latency" value={result?.metrics?.duration_ns ?? "—"} unit="nanoseconds"/><AnimatedMetric active={Boolean(result)} label="Allocated" value={result?.metrics?.bytes_allocated ?? "—"} unit="bytes"/><AnimatedMetric active={Boolean(result)} label="Allocations" value={result?.metrics?.allocations ?? "—"} unit="objects"/></div><AnimatedContent active={Boolean(metadata)} className="complexity">{metadata ? Object.entries({ best: "Best", average: "Average", worst: "Worst", memory: "Memory" }).map(([key, label]) => <dl key={key}><dt>{label}</dt><dd>{metadata.complexity[key] || "—"}</dd></dl>) : <p className="empty">Complexity metadata will appear after a run.</p>}</AnimatedContent><div className="result-box"><div className="box-heading"><h3>Operation output</h3><span>{result?.results?.length || 0} result</span></div><pre>{JSON.stringify(result?.results || "No experiment has run yet.", null, 2)}</pre></div></section></section>
    <section className="trace-panel"><div className="section-heading"><span>03</span><h2>Trace playback</h2><div className="trace-actions"><button type="button" onClick={() => setTraceIndex(Math.max(0, traceIndex - 1))}>←</button><button type="button" onClick={() => setTraceIndex(Math.min(trace.length - 1, traceIndex + 1))}>→</button><button type="button" onClick={() => setPlaying(!playing)} disabled={!trace.length}>{playing ? "Pause" : "Play"}</button></div></div><div className="trace-track"><div className="trace-line"/><div className="trace-events">{trace.length ? trace.map((event, index) => <article className={`trace-event ${index === traceIndex ? "active" : ""}`} key={`${event.sequence}-${event.type}`}><div className="marker"/><p>{event.type}</p><small>#{event.sequence} {event.detail || event.key || ""}</small></article>) : <p className="empty">Enable tracing to see the operation path.</p>}</div></div></section><footer>Deterministic workloads are identified by their structure, dataset size, operation, and seed.</footer></main>;
}

function Heading({ number, title, extra }) { return <div className="section-heading"><span>{number}</span><h2>{title}</h2>{extra && <span className="run-label">{extra}</span>}</div>; }
function Field({ label, children }) { return <label>{label}{children}</label>; }
function DatabaseView({ structures, active, trace }) { return <div className="database-view"><div className="db-toolbar"><span className="live-dot"/> Database execution path <small>{trace.length ? `${trace.length} trace events` : "trace idle"}</small></div><div className="db-flow"><div className="db-layer client-layer"><span className="layer-kicker">request</span><strong>Experiment API</strong><small>{active || "choose a structure"}</small></div><div className="flow-arrow">↓</div><div className="structure-stack">{structures.length ? structures.map((name, index) => <div className={`db-layer structure-layer ${name === active ? "active" : ""}`} key={name}><span className="layer-kicker">{index + 1}</span><strong>{name}</strong><small>{name.includes("btree") ? "ordered pages + lookup path" : "reference implementation"}</small>{trace[index] && <span className="trace-pulse">{trace[index].type}</span>}</div>) : <div className="empty">Select a structure to add it to the comparison.</div>}</div><div className="flow-arrow">↓</div><div className="db-layer result-layer"><span className="layer-kicker">output</span><strong>Results + metrics</strong><small>time · memory · trace</small></div></div></div>; }
