"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatedMetric } from "./components/AnimatedContent.jsx";
import { activeNode, applyLocalMutation, displayEvent, makeCommittedTree, makeWALRecord, mutationChanges, retiredPages, shouldShowCommittedLayers, targetForTransition } from "./lib/visualizer.js";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8080";
const OPERATIONS = ["insert", "read", "update", "delete", "range"];
const API_OPERATIONS = { insert: "set", read: "get", update: "set", delete: "delete", range: "range" };
const OPERATION_LABELS = { insert: "INSERT", read: "READ", update: "UPDATE", delete: "DELETE", range: "RANGE" };
const PATH_STEPS = ["SQL LAYER", "LOGICAL TABLE", "WAL WRITE", "BUFFER POOL", "B+TREE NODE", "DISK FLUSH"];

export default function App() {
  const [structures, setStructures] = useState([]); const [structure, setStructure] = useState("btree-memory"); const [operation, setOperation] = useState("insert");
  const [key, setKey] = useState("1"); const [value, setValue] = useState("Diana"); const [start, setStart] = useState("1"); const [end, setEnd] = useState("5"); const [liveRecords, setLiveRecords] = useState([]); const [walHistory, setWalHistory] = useState([]); const [committedTree, setCommittedTree] = useState(() => makeCommittedTree([])); const [retiredPageHistory, setRetiredPageHistory] = useState([]); const [pendingOperation, setPendingOperation] = useState(null); const [pathIndex, setPathIndex] = useState(-1); const [stepsComplete, setStepsComplete] = useState(false);
  const recordsRef = useRef(liveRecords); const treeRef = useRef(committedTree); const pendingRef = useRef(null);
  const [threadRun, setThreadRun] = useState(false);
  const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [traceIndex, setTraceIndex] = useState(-1);
  const trace = result?.trace || []; const currentEvent = trace[traceIndex]; const targetLayer = targetForTransition(pathIndex); const showCommittedLayers = shouldShowCommittedLayers({ stepsComplete, pathIndex, recordCount: liveRecords.length, walCount: walHistory.length }); const visibleTree = pendingOperation && pathIndex >= 2 ? pendingOperation.tree : committedTree;

  useEffect(() => { let cancelled = false; fetch(`${API}/api/v1/structures`).then((response) => { if (!response.ok) throw new Error("service unavailable"); return response.json(); }).then((items) => { if (!cancelled) { setStructures(items); if (!items.some((item) => item.name === structure)) setStructure(items[0]?.name || ""); } }).catch(() => { if (!cancelled) setError("Start the experiment API at http://localhost:8080, then refresh this page."); }); return () => { cancelled = true; }; }, [structure]);
  async function runExperiment(event) { event.preventDefault(); if (pendingRef.current) return; const currentRecords = recordsRef.current; const currentTree = treeRef.current; if (operation === "update" && !currentRecords.some((record) => String(record.key) === String(key))) { setError(`Cannot update missing key ${key}.`); return; } setLoading(true); setError(""); setTraceIndex(-1); setPathIndex(0); setStepsComplete(false); const request = { structure, dataset_size: 0, seed: 0, trace: true, operations: [{ name: API_OPERATIONS[operation], key, value, start, end }] }; try { const response = await fetch(`${API}/api/v1/experiments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); const body = await response.json(); if (!response.ok) throw new Error(body.code || "experiment_failed"); const changesState = isMutation(operation) && mutationChanges(currentRecords, operation, key, value); const nextRecords = changesState ? applyLocalMutation(currentRecords, operation, key, value) : currentRecords; const nextTree = changesState ? makeCommittedTree(nextRecords, currentTree) : currentTree; const nextPending = { operation, key: String(key), value: String(value), records: nextRecords, tree: nextTree, mutates: changesState, walRecorded: false }; pendingRef.current = nextPending; setResult(body); setTraceIndex(body.trace?.length ? 0 : -1); setPendingOperation(nextPending); } catch (runError) { setError(`Could not run experiment: ${runError.message}.`); setPathIndex(-1); } finally { setLoading(false); } }
  function recordPendingWAL() { const pending = pendingRef.current; if (!pending || pending.walRecorded || !pending.mutates) return; setWalHistory((history) => [...history, makeWALRecord(pending, history.length + 1)]); const nextPending = { ...pending, walRecorded: true }; pendingRef.current = nextPending; setPendingOperation(nextPending); }
  function publishPending() { const pending = pendingRef.current; if (!pending) return; if (pending.mutates) { if (!pending.walRecorded) setWalHistory((history) => [...history, makeWALRecord(pending, history.length + 1)]); const previousTree = treeRef.current; recordsRef.current = pending.records; treeRef.current = pending.tree; setLiveRecords(pending.records); setRetiredPageHistory((pages) => [...pages, ...retiredPages(previousTree, pending.tree)]); setCommittedTree(pending.tree); } pendingRef.current = null; setPendingOperation(null); }
  function finishSteps() { publishPending(); setPathIndex(-1); setStepsComplete(true); }
  function advancePath() { if (pathIndex === 0) recordPendingWAL(); if (pathIndex === 3) publishPending(); setPathIndex((index) => Math.min(PATH_STEPS.length - 1, index + 1)); }
  function simulateThreads() { setThreadRun(true); window.setTimeout(() => setThreadRun(false), 1800); }
  const complexity = structures.find((item) => item.name === structure)?.complexity?.find((item) => item.operation === API_OPERATIONS[operation]);

  return <main className="shell" data-build="persistent-visualizer-v2"><header className="topbar"><div className="brand-lockup"><span className="brand-mark">A</span><div><strong>AlgoDB Lab</strong><span>database internals debugger</span></div></div><nav className="topnav engine-tabs" aria-label="Data structure engines"><button className="nav-active">B+ TREE</button><button disabled>LSM-TREE</button><button disabled>SKIPLIST</button><button disabled>HASH INDEX</button></nav></header>
    <section className="debug-toolbar"><div className="toolbar-group"><span className="toolbar-label">structure</span><strong>B+ TREE</strong></div><div className="toolbar-group"><span className="toolbar-label">operation</span><div className="toolbar-tabs">{OPERATIONS.map((item) => <button type="button" className={operation === item ? "selected" : ""} key={item} onClick={() => setOperation(item)}>{OPERATION_LABELS[item]}</button>)}</div></div><form className="quick-run" onSubmit={runExperiment}>{operation === "range" ? <><label>START<input placeholder="1" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>END<input placeholder="5" value={end} onChange={(event) => setEnd(event.target.value)} /></label></> : <><label>KEY<input placeholder="1" value={key} onChange={(event) => setKey(event.target.value)} /></label>{(operation === "insert" || operation === "update") && <label>VALUE<input placeholder="Diana" value={value} onChange={(event) => setValue(event.target.value)} /></label>}</>}<button disabled={loading}>{loading ? "RUNNING" : "EXECUTE"}</button></form></section>
    <section className={`debug-layout ${pathIndex >= 0 ? "drawer-reserved" : ""}`}><aside className="data-sidebar"><div className={`logical-table-section ${targetLayer === "logical-table" ? "path-highlight" : ""}`}><SectionHeading number="01" title="Logical table" extra={`${liveRecords.length} rows`}/><TableView records={liveRecords} activeKey={key} onSelect={(record) => { setKey(record.key); setValue(record.value); }}/><div className="sidebar-controls"><p className="form-error" role="alert">{error}</p></div></div><ThreadWorkers active={Boolean(result)} running={threadRun} onSimulate={simulateThreads} /></aside><section className="engine-stage"><div className="stage-heading"><div><span className="stage-kicker">02 / storage engine</span><h1>B+Tree storage engine</h1></div></div><div className="data-path" aria-label="Execution data path">{PATH_STEPS.map((stepName, index) => <span className={index === pathIndex ? "active" : ""} key={stepName}>{stepName}{index < PATH_STEPS.length - 1 && <b>→</b>}</span>)}</div><div className="engine-panel"><BTreeDiagram tree={visibleTree} visible={showCommittedLayers || pathIndex >= 3} active={!stepsComplete && targetLayer === "btree-node" ? activeNode(currentEvent) || `key:${key}` : ""} durable={false}/><div className={`buffer-panel ${targetLayer === "buffer-pool" ? "path-highlight" : ""}`}><div className="subheading">Buffer pool <small>RAM pages</small></div>{showCommittedLayers || pathIndex >= 2 ? <DiskPages tree={visibleTree} durable={false}/> : <StagePlaceholder label="Awaiting WAL write"/>}</div></div><FlowStrip className={targetLayer === "wal" ? "path-highlight" : ""} title="Write-ahead log" subtitle={`${walHistory.length} mutation${walHistory.length === 1 ? "" : "s"}`}>{showCommittedLayers || pathIndex >= 1 ? <LogStrip history={walHistory} pending={pendingOperation}/> : <StagePlaceholder label="Awaiting logical mutation"/>}</FlowStrip><FlowStrip className={targetLayer === "disk" ? "path-highlight" : ""} title="Disk · physical data pages" subtitle={`${committedTree.leaves.length} live pages · ${retiredPageHistory.length} retired`}>{showCommittedLayers || pathIndex >= 4 ? <DiskPages tree={committedTree} durable={true} retiredPages={retiredPageHistory}/> : <StagePlaceholder label="Awaiting disk flush"/>}</FlowStrip><FlowStrip className="diagnostic-dock" title="Diagnostic console" subtitle={trace.length ? `${traceIndex + 1} / ${trace.length} events` : "ready · execute to trace"}><TraceConsole trace={trace} index={traceIndex}/></FlowStrip></section></section><StepDrawer stepIndex={pathIndex} onClose={finishSteps} onNext={() => pathIndex === PATH_STEPS.length - 1 ? finishSteps() : advancePath()} onPrevious={() => setPathIndex((index) => Math.max(0, index - 1))} keyValue={key} value={value}/><footer className="live-footer"><Metrics result={result} complexity={complexity}/></footer></main>;
}

function isMutation(operation) { return operation === "insert" || operation === "update" || operation === "delete"; }

function SectionHeading({ number, title, extra }) { return <div className="section-heading"><span className="section-number">{number}</span><h2>{title}</h2>{extra && <span className="section-extra">{extra}</span>}</div>; }
function Field({ label, children }) { return <label className="field">{label}{children}</label>; }
function TableView({ records, activeKey, onSelect }) { return <div className="table-card" data-testid="logical-records"><div className="table-toolbar"><span>records</span><small>{records.length ? `${records.length} preview rows` : "Run a workload to load records"}</small></div>{records.length ? <div className="table-scroll"><table><thead><tr><th>primary key</th><th>value</th></tr></thead><tbody>{records.slice(0, 12).map((record) => <tr className={String(record.key) === String(activeKey) ? "row-active" : ""} key={record.key} onClick={() => onSelect(record)}><td>{record.key}</td><td>{record.value}</td></tr>)}</tbody></table></div> : <p className="empty-table">No sample records yet.</p>}</div>; }
function StagePlaceholder({ label }) { return <div className="stage-placeholder">{label}</div>; }
function BTreeDiagram({ tree, visible = true, active, durable }) { return <div className="tree-card" data-testid={durable ? "disk-pages" : "ram-tree"}><div className="tree-toolbar"><span className="tree-title">{durable ? "disk pages" : "RAM - In-Memory Layer"}</span><small>root → internal separators → linked leaves</small></div>{visible ? <div className="tree-canvas"><div className={`tree-node root-node ${active === tree.root.id ? "node-active" : ""}`}><span className="node-label">ROOT / INTERNAL</span><div className="node-entries">{tree.root.entries.length ? tree.root.entries.map((entry) => <span key={entry.key}>{entry.key || "lower bound"} <b>{entry.value}</b></span>) : <span>lower bound → {tree.leaves[0].id}</span>}</div></div><div className="tree-connectors">{tree.leaves.map((leaf) => <span key={leaf.id}>│</span>)}</div><div className="leaf-row">{tree.leaves.map((leaf) => <div className={`tree-node leaf-node ${active === leaf.id || active === `page-${leaf.id}` || leaf.entries.some((entry) => active === `key:${entry.key}`) ? "node-active" : ""}`} key={leaf.id}><span className="node-label">{durable ? leaf.id.toUpperCase() : leaf.id.toUpperCase()} / LEAF</span>{leaf.entries.length ? leaf.entries.map((entry) => <span className={`kv ${active === `key:${entry.key}` ? "entry-active" : ""}`} key={entry.key}><b>{entry.key}</b><em>{entry.value}</em></span>) : <span className="empty-node">empty</span>}</div>)}</div></div> : <StagePlaceholder label="Awaiting buffer pool mutation" />}</div>; }
function DiskPages({ tree, durable, retiredPages = [] }) { return <div className="disk-pages"><div className="live-page-grid">{tree.leaves.slice(0, 4).map((leaf) => <div className="disk-page" key={leaf.id}><span>{leaf.id.toUpperCase()} · {leaf.entries.length} keys</span><div>{leaf.entries.slice(0, 3).map((entry) => <code key={entry.key}>{entry.key} <b>{entry.value}</b></code>)}</div></div>)}</div>{durable && retiredPages.length > 0 && <div className="retired-page-grid"><small>RETIRED PAGES · AWAITING REUSE</small>{retiredPages.slice(-4).map((page) => <div className="disk-page retired-page" key={`${page.id}-${page.entries.length}`}><span>{page.id.toUpperCase()} · retired</span><div>{page.entries?.slice(0, 3).map((entry) => <code key={entry.key}>{entry.key} <b>{entry.value}</b></code>)}</div></div>)}</div>}</div>; }
function LogStrip({ history, pending }) { return <div className="log-strip">{history.map((entry) => <div className="log-entry" key={entry.id}><small>LSN:{entry.id} · APPEND-ONLY</small><strong>{OPERATION_LABELS[entry.operation]}</strong><code>{entry.key}{entry.value ? `  ${entry.value}` : ""}</code></div>)}{pending?.mutates && !pending.walRecorded && <div className="log-entry pending-log"><small> NEXT · PENDING</small><strong>{OPERATION_LABELS[pending.operation]}</strong><code>{pending.key}{pending.value ? `  ${pending.value}` : ""}</code></div>}{!history.length && !pending?.mutates && <StagePlaceholder label="No mutations recorded"/>}</div>; }
function StepInspector({ event, index, total }) { return <aside className="step-inspector"><div className="inspector-kicker">CURRENT STEP</div><strong>{event ? displayEvent(event) : "Ready"}</strong><span>{event ? `${index + 1} of ${total}` : "Execute to inspect the path"}</span><p>{event ? event.detail || `The engine is visiting ${event.layer || "the storage layer"}.` : "Playback opens a detail card for every lookup, comparison, traversal, and result."}</p>{event?.key && <code>key: {event.key}</code>}{event?.node_id && <code>node: {event.node_id}</code>}{event?.page_id && <code>page: {event.page_id}</code>}</aside>; }
function StepList({ trace, index, onSelect }) { return <div className="step-list"><div className="subheading">Execution steps <small>{trace.length || 0} events</small></div>{trace.length ? trace.slice(0, 8).map((event, stepIndex) => <button type="button" className={stepIndex === index ? "active" : ""} onClick={() => onSelect(stepIndex)} key={`${event.sequence}-${event.type}`}><span>{String(stepIndex + 1).padStart(2, "0")}</span><strong>{displayEvent(event)}</strong><small>{event.layer || "engine"}</small></button>) : <p>Steps appear after execution.</p>}</div>; }
function ThreadWorkers({ active, running, onSimulate }) { return <div className="thread-workers"><div className="subheading">Thread workers <button type="button" onClick={onSimulate}>SIMULATE</button></div>{[["T1", "teal"], ["T2", "purple"], ["T3", "gold"]].map(([name, color], index) => <div className="thread-row" key={name}><i className={color} /> <strong>{name}</strong><span>{running ? (index === 1 ? "BLOCKED" : "RUNNING") : active ? "IDLE" : "IDLE"}</span></div>)}</div>; }
function StepDrawer({ stepIndex, onClose, onNext, onPrevious, keyValue, value }) { if (stepIndex < 0) return null; const descriptions = [{ title: "SQL Layer → Logical Table", body: "Your operation enters the SQL boundary and is resolved against the logical table. No bytes have been persisted yet." }, { title: "Logical Table → WAL Write", body: "The logical mutation is recorded as one ordered operation before the tree is changed." }, { title: "WAL Write → Buffer Pool", body: "The operation is admitted to the in-memory page working set. Existing pages remain available to readers." }, { title: "Buffer Pool → B+Tree Node", body: "The tree searches sorted separators, chooses a leaf, and applies this single key/value mutation." }, { title: "B+Tree Node → Disk Flush", body: "The updated page is serialized and prepared for durable publication. The committed root remains protected until flush completes." }, { title: "Disk Flush → Result", body: "The operation returns its result and the trace can be replayed without changing the stored data." }]; const current = descriptions[stepIndex]; const highlighted = PATH_STEPS[stepIndex + 1] || "RESULT"; return <aside className="step-drawer" aria-label="Execution step"><div className="drawer-top"><span>STEP {stepIndex + 1} OF {descriptions.length}</span><button type="button" onClick={onClose} aria-label="Close step panel">×</button></div><div className="drawer-number">{stepIndex + 1}</div><h2>{current.title}</h2><div className="drawer-card"><p>{current.body}</p><p><strong>Key:</strong> {keyValue} · <strong>Value:</strong> “{value}”</p><p className="drawer-note">Highlighted: <b>{highlighted}</b></p></div><div className="drawer-progress">{descriptions.map((_, index) => <i className={index === stepIndex ? "active" : index < stepIndex ? "complete" : ""} key={index} />)}</div><div className="drawer-actions"><button type="button" onClick={onPrevious} disabled={stepIndex === 0}>BACK</button><button type="button" onClick={onNext}>{stepIndex === descriptions.length - 1 ? "DONE" : "NEXT →"}</button></div></aside>; }
function FlowStrip({ title, subtitle, children, className = "" }) { return <section className={`flow-strip ${className}`}><div className="flow-heading"><span>● &nbsp;{title}</span><small>{subtitle}</small></div>{children}</section>; }
function Metrics({ result, complexity }) { return <><div className="metric-grid"><AnimatedMetric active={Boolean(result)} label="Latency" value={result?.metrics?.duration_ns ?? "—"} unit="ns"/><AnimatedMetric active={Boolean(result)} label="Allocated" value={result?.metrics?.bytes_allocated ?? "—"} unit="bytes"/><AnimatedMetric active={Boolean(result)} label="Allocations" value={result?.metrics?.allocations ?? "—"} unit="objects"/></div><div className="complexity-row">{[["best", "Best"], ["average", "Average"], ["worst", "Worst"], ["memory", "Memory"]].map(([key, label]) => <div key={key}><small>{label}</small><strong>{complexity?.complexity?.[key] || "—"}</strong></div>)}</div></>; }
function TraceConsole({ trace, index }) { return <div className="trace-console">{trace.length ? trace.map((event, eventIndex) => <div className={`trace-line ${eventIndex === index ? "current" : ""}`} key={`${event.sequence}-${event.type}`}><span className="trace-sequence">{String(event.sequence).padStart(2, "0")}</span><span className="trace-kind">{displayEvent(event)}</span><span className="trace-detail">{event.layer || "engine"}{event.key ? ` · ${event.key}` : ""}{event.detail ? ` · ${event.detail}` : ""}</span></div>) : <p className="empty-table">Enable tracing, then run an operation to see comparisons and page visits here.</p>}</div>; }
