"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatedMetric } from "./components/AnimatedContent.jsx";
import { activeNode, displayEvent, displayStructure, makeBTree, resultSummary } from "./lib/visualizer.js";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8080";
const OPERATIONS = ["get", "set", "delete", "range"];

export default function App() {
  const [structures, setStructures] = useState([]); const [structure, setStructure] = useState("btree-memory"); const [operation, setOperation] = useState("get");
  const [datasetSize, setDatasetSize] = useState(24); const [seed, setSeed] = useState(42); const [key, setKey] = useState("key-000008"); const [value, setValue] = useState("Ada"); const [start, setStart] = useState("key-000004"); const [end, setEnd] = useState("key-000012"); const [captureTrace, setCaptureTrace] = useState(true);
  const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [traceIndex, setTraceIndex] = useState(-1); const [playing, setPlaying] = useState(false);
  const trace = result?.trace || []; const currentEvent = trace[traceIndex]; const tree = useMemo(() => makeBTree(result?.dataset || []), [result]);

  useEffect(() => { let cancelled = false; fetch(`${API}/api/v1/structures`).then((response) => { if (!response.ok) throw new Error("service unavailable"); return response.json(); }).then((items) => { if (!cancelled) { setStructures(items); if (!items.some((item) => item.name === structure)) setStructure(items[0]?.name || ""); } }).catch(() => { if (!cancelled) setError("Start the experiment API at http://localhost:8080, then refresh this page."); }); return () => { cancelled = true; }; }, [structure]);
  useEffect(() => { if (!playing || !trace.length) return undefined; const timer = setInterval(() => setTraceIndex((current) => { if (current >= trace.length - 1) { setPlaying(false); return current; } return current + 1; }), 650); return () => clearInterval(timer); }, [playing, trace.length]);

  async function runExperiment(event) { event.preventDefault(); setLoading(true); setError(""); setPlaying(false); setTraceIndex(-1); const request = { structure, dataset_size: Number(datasetSize), seed: Number(seed), trace: captureTrace, operations: [{ name: operation, key, value, start, end }] }; try { const response = await fetch(`${API}/api/v1/experiments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); const body = await response.json(); if (!response.ok) throw new Error(body.code || "experiment_failed"); setResult(body); setTraceIndex(body.trace?.length ? 0 : -1); } catch (runError) { setError(`Could not run experiment: ${runError.message}.`); } finally { setLoading(false); } }
  function step(direction) { setTraceIndex((current) => Math.max(0, Math.min(trace.length - 1, current + direction))); }
  const complexity = structures.find((item) => item.name === structure)?.complexity?.find((item) => item.operation === operation);

  return <main className="shell"><header className="topbar"><div><p className="eyebrow">AlgoDB Lab / storage engine visualizer</p><h1>See the operation move through the database.</h1><p className="lede">Run one reproducible CRUD operation and watch the table, B+Tree nodes, pages, and trace update together.</p></div><div className="engine-badge"><span className="live-dot" /> Local experiment engine<br /><small>seed {seed} · {datasetSize} records</small></div></header>
    <section className="lab-grid"><aside className="control-rail"><SectionHeading number="01" title="Run a workload"/><form onSubmit={runExperiment}><Field label="Implementation"><select value={structure} onChange={(event) => setStructure(event.target.value)}>{structures.map((item) => <option key={item.name} value={item.name}>{displayStructure(item.name)}</option>)}</select></Field><Field label="Operation"><div className="operation-tabs">{OPERATIONS.map((item) => <button type="button" className={operation === item ? "selected" : ""} key={item} onClick={() => setOperation(item)}>{item}</button>)}</div></Field><div className="form-grid"><Field label="Dataset"><input type="number" min="0" max="1000" value={datasetSize} onChange={(event) => setDatasetSize(event.target.value)}/></Field><Field label="Seed"><input type="number" min="0" value={seed} onChange={(event) => setSeed(event.target.value)}/></Field></div>{operation !== "range" && <><Field label="Key"><input value={key} onChange={(event) => setKey(event.target.value)} placeholder="key-000008"/></Field>{operation === "set" && <Field label="Value"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Ada"/></Field>}</>}{operation === "range" && <div className="form-grid"><Field label="From"><input value={start} onChange={(event) => setStart(event.target.value)}/></Field><Field label="To"><input value={end} onChange={(event) => setEnd(event.target.value)}/></Field></div>}<label className="check"><input type="checkbox" checked={captureTrace} onChange={(event) => setCaptureTrace(event.target.checked)}/> Capture execution trace</label><button className="run-button" disabled={loading}>{loading ? "Running..." : "Run operation"}<span>→</span></button><p className="form-error" role="alert">{error}</p></form><div className="legend"><span><i className="swatch memory"/> memory</span><span><i className="swatch disk"/> disk page</span><span><i className="swatch active"/> current step</span></div></aside>
      <section className="visual-column"><SectionHeading number="02" title="Logical table" extra={resultSummary(result)}/><TableView records={result?.dataset || []} activeKey={key} onSelect={(record) => { setKey(record.key); setValue(record.value); }}/><SectionHeading number="03" title="Physical B+Tree" extra={displayStructure(structure)}/><BTreeDiagram tree={tree} active={activeNode(currentEvent)} durable={structure === "btree-durable"}/><Metrics result={result} complexity={complexity}/></section></section>
    <section className="trace-section"><div className="section-heading"><SectionHeading number="04" title="Execution trace" extra={trace.length ? `${traceIndex + 1} / ${trace.length}` : "No run yet"}/><div className="trace-actions"><button type="button" onClick={() => step(-1)} disabled={!trace.length}>←</button><button type="button" onClick={() => step(1)} disabled={!trace.length}>→</button><button type="button" onClick={() => setPlaying(!playing)} disabled={!trace.length}>{playing ? "Pause" : "Play"}</button></div></div><TraceConsole trace={trace} index={traceIndex}/></section><footer>Every run uses the selected seed and dataset. The diagram shows the bounded sample returned by the experiment API.</footer></main>;
}

function SectionHeading({ number, title, extra }) { return <div className="section-heading"><span className="section-number">{number}</span><h2>{title}</h2>{extra && <span className="section-extra">{extra}</span>}</div>; }
function Field({ label, children }) { return <label className="field">{label}{children}</label>; }
function TableView({ records, activeKey, onSelect }) { return <div className="table-card"><div className="table-toolbar"><span>records</span><small>{records.length ? `${records.length} preview rows` : "Run a workload to load records"}</small></div>{records.length ? <div className="table-scroll"><table><thead><tr><th>primary key</th><th>value</th></tr></thead><tbody>{records.slice(0, 12).map((record) => <tr className={record.key === activeKey ? "row-active" : ""} key={record.key} onClick={() => onSelect(record)}><td>{record.key}</td><td>{record.value}</td></tr>)}</tbody></table></div> : <p className="empty-table">No sample records yet.</p>}</div>; }
function BTreeDiagram({ tree, active, durable }) { return <div className="tree-card"><div className="tree-toolbar"><span className="tree-title">{durable ? "disk pages" : "memory nodes"}</span><small>root → internal separators → linked leaves</small></div><div className="tree-canvas"><div className={`tree-node root-node ${active === tree.root.id ? "node-active" : ""}`}><span className="node-label">ROOT / INTERNAL</span><div className="node-entries">{tree.root.entries.length ? tree.root.entries.map((entry) => <span key={entry.key}>{entry.key || "lower bound"} <b>{entry.value}</b></span>) : <span>lower bound → leaf-1</span>}</div></div><div className="tree-connectors">{tree.leaves.map((leaf) => <span key={leaf.id}>│</span>)}</div><div className="leaf-row">{tree.leaves.map((leaf) => <div className={`tree-node leaf-node ${active === leaf.id || active === `page-${leaf.id}` || leaf.entries.some((entry) => active === `key:${entry.key}`) ? "node-active" : ""}`} key={leaf.id}><span className="node-label">{durable ? `PAGE ${leaf.id.split("-")[1]}` : leaf.id.toUpperCase()} / LEAF</span>{leaf.entries.length ? leaf.entries.map((entry) => <span className={`kv ${active === `key:${entry.key}` ? "entry-active" : ""}`} key={entry.key}><b>{entry.key}</b><em>{entry.value}</em></span>) : <span className="empty-node">empty</span>}</div>)}</div></div></div>; }
function Metrics({ result, complexity }) { return <><div className="metric-grid"><AnimatedMetric active={Boolean(result)} label="Latency" value={result?.metrics?.duration_ns ?? "—"} unit="ns"/><AnimatedMetric active={Boolean(result)} label="Allocated" value={result?.metrics?.bytes_allocated ?? "—"} unit="bytes"/><AnimatedMetric active={Boolean(result)} label="Allocations" value={result?.metrics?.allocations ?? "—"} unit="objects"/></div><div className="complexity-row">{[["best", "Best"], ["average", "Average"], ["worst", "Worst"], ["memory", "Memory"]].map(([key, label]) => <div key={key}><small>{label}</small><strong>{complexity?.complexity?.[key] || "—"}</strong></div>)}</div></>; }
function TraceConsole({ trace, index }) { return <div className="trace-console">{trace.length ? trace.map((event, eventIndex) => <div className={`trace-line ${eventIndex === index ? "current" : ""}`} key={`${event.sequence}-${event.type}`}><span className="trace-sequence">{String(event.sequence).padStart(2, "0")}</span><span className="trace-kind">{displayEvent(event)}</span><span className="trace-detail">{event.layer || "engine"}{event.key ? ` · ${event.key}` : ""}{event.detail ? ` · ${event.detail}` : ""}</span></div>) : <p className="empty-table">Enable tracing, then run an operation to see comparisons and page visits here.</p>}</div>; }
